spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gainzpad?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
#  thymeleaf:
#    cache: false
#    prefix: file:./src/main/resources/templates/
#    check-template-location: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true

#logging:
#  level:
#    root: INFO
#    org.springframework: DEBUG
